### PR TITLE
Few big fixes

### PR DESCRIPTION
**Pull request by mr0ng**
1. Added UI to floor, so users can mute themselves, mute speaker
2.
Fixed ability to detect voice - should eliminate echos.
3. Improved
voice detection bubble icon (See image)
4. Improved camera clipping

### CODE REVIEW

**Comment by branchbark** [comment]
Hi @mr0ng, when you walk around the scene, you see some of your own avatar's body within your FOV on the device.  What setting was used in the past so that you would not see your own avatar?

image

**Comment by mr0ng** [comment]
More commits added. See commits for more detail.

**Comment by juliedriver** [comment]
The skinned mesh renderer in Robot2 (under KyleRobot in the hierarchy) is default unchecked. Which means this:

where_am_i

When I check that checkbox I can see myself in the scene:

there_i_am

Also note that the HUD in the game window is missing top section on the left and the indicator on the bottom right should show 3 white buttons.

**Comment by mr0ng** [comment]
Yup, making the robot invisible is by design so users can't see themselves. The app is intended to be used from a first person perspective. We can include the ability to show yourself if using it from a 3rd person POV.

Sent via Outlook for Android

________________________________

**Comment by branchbark** [comment]
@mr0ng Do we have the ability to limit some of the photon in-game menu options for the external end-users? Also, one of the tooltip options on the disc in the center of the scene should inform the end user to toggle the menu hide/ display by air-tapping the white disc.

**Comment by mr0ng** [comment]
Changed disk text to "Tap to toggle menu"
Changed text on menu items to make them more clear
Removed some advanced menu items.

**Comment by mr0ng** [comment]
Added analytics for menu board and menu disk

**Comment by mr0ng** [comment]
Added Practical Analytics to all UI items

**Comment by branchbark** [comment]
Looks good, except we need to update the title of the 'Menu' scene from MR Hangout to myxd3D.

**Pull request merged**
